# Generated by Django 4.2.3 on 2023-08-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articlesection_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesection',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_sections', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='articlesection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_sections', to='articles.section'),
        ),
    ]
